<?php
define( "LS_TITLE_MAIN", "Generador de código para procedimientos almacenados de Oracle en paginas PHP" );
define( "LS_TITLE_HELP", "Instrucciones:" );
define( "LS_TITLE_SKELETON", "Este es un ejemplo de cómo utilizar la clase" );
define( "LS_TITLE_CLASS", "Este es el código de la clase" );
define( "LS_INPUTDES_PACK", "Paquete" );
define( "LS_INPUTDES_PROC", "Procedimiento" );
define( "LS_INPUTDES_WARN", "Impresion de Alertas" );
define( "LS_INPUTDES_FILE", "Escribe en archivo" );
define( "LS_INPUTDES_OWRW", "Reemplace si existe el archivo" );
define( "LS_INPUTDES_SCREEN", "Muestra clase en la pantalla");
define( "LS_INPUTDES_PACK_DES", "Nombre del paquete. Sí el procedimiento almacenado no esta en un paquete; dejarlo vacío" );
define( "LS_INPUTDES_PROC_DES", "Nombre del procedimiento." );
define( "LS_INPUTDES_WARN_DES", "Hay tipos de argumentos que el generador no conoce.<br/>Cuando encuentra un tipo que no reconoce intenta conjeturar. Esta opción marca esas líneas con un comentario." );
define( "LS_INPUTDES_FILE_DES", "El resultado se escribe al archivo (ruta incluida) especificado. Deje vacío para recibir el resultado en la pantalla.<br/>La ruta es relativa a la raíz del sitio" );
define( "LS_INPUTDES_OWRW_DES", "Con esta opcion seleccionada, si el archivo existe será sobreescrito." );
define( "LS_INPUTDES_SCREEN_DES", "Muestra el código PHP de la clase en la pantalla, no sólo el ejemplo de cómo usarlo." );
define( "LS_NO_PACK_DES", " -- Proc sin paquete -- " );
define( "LS_MAKE_ALL_DES", " -- Haz todos -- " );
define( "LS_CHOOSE_PROC_DES", " -- Eligir Procedimiento -- " );
define( "LS_BROWSE_DES", "Buscar" );
define( "LS_SUBMIT_DES", "Enviar" );
define( "LS_CANCEL_DES", "Cancelar" );
define( "LS_ERR_CONNECT", "Error al conectarse a la base de datos. Asegúrese de que la configuración en config.php es correcta y de que la base de datos está funcionando y que OCI está instalada ");
define( "LS_ERR_CANT_WRITE_FILE", "No se puede crear el archivo" );
define( "LS_ERR_NOT_INIT", "Run make_class first" );
define( "LS_ERR_NO_FILENAME", "No puedo escribir a un archivo sin nombre" );
define( "LS_ERR_DIR_NOT_SET", "Directorio no establecido (config.php)" );
define( "LS_ERR_DIR_DOES_NOT_EXIST", "El directorio no existe" );
define( "LS_ERR_DIR_READONLY", "El directorio es de sólo lectura" );
define( "LS_ERR_FILE_EXISTS", "El archivo existe y no se ha seleccionado Sobrescribir" );
define( "LS_ERR_FILE_EXISTS_READONLY", "El archivo existe y es de sólo lectura" );
?>
