<?php
define( "LS_TITLE_MAIN", "Code wizard for calling Oracle Stored Procedures from PHP" );
define( "LS_TITLE_HELP", "Instructions:" );
define( "LS_TITLE_SKELETON", "This is an example of how to use the class" );
define( "LS_TITLE_CLASS", "This is the code for the class" );
define( "LS_INPUTDES_PACK", "Package" );
define( "LS_INPUTDES_PROC", "Procedure" );
define( "LS_INPUTDES_WARN", "Print Warnings" );
define( "LS_INPUTDES_FILE", "Write to file" );
define( "LS_INPUTDES_OWRW", "Replace file if it exists" );
define( "LS_INPUTDES_SCREEN", "Print class on screen");
define( "LS_INPUTDES_PACK_DES", "Name of the package where the stored procedure resides." );
define( "LS_INPUTDES_PROC_DES", "Name of the stored procedure." );
define( "LS_INPUTDES_WARN_DES", "This tool does not recognize all of the Oracle datatypes.<br/>If an unknown datatype is ecounterd, it is marked with a comment." );
define( "LS_INPUTDES_FILE_DES", "Save the result to a file. The file name is relative to the document root of the web server." );
define( "LS_INPUTDES_OWRW_DES", "With this option checked, file will be overwritten if it exists." );
define( "LS_INPUTDES_SCREEN_DES", "Shows the PHP-code of the class on the screen, not just the example on how to use it" );
define( "LS_NO_PACK_DES", " -- Proc without package -- " );
define( "LS_MAKE_ALL_DES", " -- Make all -- " );
define( "LS_CHOOSE_PROC_DES", " -- Select Procedure -- " );
define( "LS_BROWSE_DES", "Browse" );
define( "LS_SUBMIT_DES", "Submit" );
define( "LS_CANCEL_DES", "Cancel" );
define( "LS_ERR_CONNECT", "Failed to connect to the database. Make sure that the settings in config.php is correct and that the database is up and running and that OCI is installed" );
define( "LS_ERR_CANT_WRITE_FILE", "Can't create file" );
define( "LS_ERR_NOT_INIT", "Run make_class first" );
define( "LS_ERR_NO_FILENAME", "Can't write to file with no name" );
define( "LS_ERR_DIR_NOT_SET", "Directory not set (config.php)" );
define( "LS_ERR_DIR_DOES_NOT_EXIST", "Directory does not exist" );
define( "LS_ERR_DIR_READONLY", "Directory is read only" );
define( "LS_ERR_FILE_EXISTS", "File exist and Overwrite is not selected" );
define( "LS_ERR_FILE_EXISTS_READONLY", "File exist and is read only" );
?>
