<?php
define( "LS_TITLE_MAIN", "Oracle PHP kodmagiker" );
define( "LS_TITLE_HELP", "Instruktioner:" );
define( "LS_TITLE_SKELETON", "Detta är ett exempel på hur klassen kan användas" );
define( "LS_TITLE_CLASS", "Detta är koden för klassen" );
define( "LS_INPUTDES_PACK", "Paket" );
define( "LS_INPUTDES_PROC", "Procedur" );
define( "LS_INPUTDES_WARN", "Inkludera varningar" );
define( "LS_INPUTDES_FILE", "Spara som fil" );
define( "LS_INPUTDES_OWRW", "Skriv över om den finns" );
define( "LS_INPUTDES_SCREEN", "Visa kod för Class på skärmen");
define( "LS_INPUTDES_PACK_DES", "Paketets namn. Lämna blank om proceduren inte finns i ett paket" );
define( "LS_INPUTDES_PROC_DES", "Procedurens namn." );
define( "LS_INPUTDES_WARN_DES", "Några datatyper går inte att känna igen.<br/>Om en okänd datatyp hittas markeras denna rad med en kommentar." );
define( "LS_INPUTDES_FILE_DES", "Spara den genererade koden i en fil. Filnamnet är relativt webbserverns dokumentrot." );
define( "LS_INPUTDES_OWRW_DES", "Om det finns en fil med samma namn skrivs den över utan att klaga eller fråga." );
define( "LS_INPUTDES_SCREEN_DES", "Visar koden för php-klassen på skärmen och inte bara ett exempel på hur den kan användas." );
define( "LS_NO_PACK_DES", " -- Proc utan paket -- " );
define( "LS_MAKE_ALL_DES", " -- Skapa alla -- " );
define( "LS_CHOOSE_PROC_DES", " -- Välj Procedure -- " );
define( "LS_BROWSE_DES", "Utforska" );
define( "LS_SUBMIT_DES", "Skicka" );
define( "LS_CANCEL_DES", "Avbryt" );
define( "LS_ERR_CONNECT", "Det gick inte att anslutat till databasen. Kontrollera att inställningarna i config.php är korrekta, att databasen är i drift samtt att OCI är installerat." );
define( "LS_ERR_CANT_WRITE_FILE", "Kan inte skapa filen" );
define( "LS_ERR_NOT_INIT", "Run make_class first" );
define( "LS_ERR_NO_FILENAME", "Kan inte skriva till namnlös fil" );
define( "LS_ERR_DIR_NOT_SET", "Sökväg saknas (config.php)" );
define( "LS_ERR_DIR_DOES_NOT_EXIST", "Angiven mapp existerar inte" );
define( "LS_ERR_DIR_READONLY", "Angiven mapp är skrivskyddad" );
define( "LS_ERR_FILE_EXISTS", "Filen finns redan, välj '" . LS_INPUTDES_OWRW ."'" );
define( "LS_ERR_FILE_EXISTS_READONLY", "Filen finns och är skrivskyddad" );
?>
